//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InformationDbEntities : DbContext
    {
        public InformationDbEntities()
            : base("name=InformationDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<testInformation> testInformation { get; set; }
    
        public virtual ObjectResult<MyBestProcedurina_Result> MyBestProcedurina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyBestProcedurina_Result>("MyBestProcedurina");
        }
    }
}
